"use strict";
const firstName = localStorage.getItem("first-name");
const surname = localStorage.getItem("surname");
document.getElementById("cv-full-name").textContent = `${firstName} ${surname}`;
const description = localStorage.getItem("description");
document.getElementById("description").textContent = description;
const mail = localStorage.getItem("mail");
document.getElementById("mail").textContent = mail;
const mobNumber = localStorage.getItem("mob-number");
document.getElementById("mob-number").textContent = mobNumber;
